#pragma once
// PIN allccation
#define MOTOR_PWM1 32
#define MOTOR_PWM2 26
#define MOTOR_PWM3 33
#define MOTOR_PWM4 27
#define MOTOR_PWM5 25
#define MOTOR_PWM6 14

#define BUILTIN_LED 2
#define LED_DEBUG_PIN 12
#define SW_DEBUG_PIN 34
#define PMW3901_CS_PIN 5

// System setting
#define SAMPLING_POSITION_CONTROL_TIME_MS 20
#define SAMPLING_ATTITUDE_CONTROL_TIME_MS 10
#define SAMPLING_ANGVEL_CONTROL_TIME_MS 1
#define RECEIVE_DATA_SIZE 7
#define LIMIT_MOTOR 255

// Debug setting
//#define DEBUG_IMU_ATTITUDE
//#define DEBUG_IMU_ANGVEL
//#define DEBUG_IMU_ACCELERATION

//#define DEBUG_RECV_SWITCH
//#define DEBUG_RECV_JOYSTICK

//#define DEBUG_FLOW_PIXEL_DELTA
//#define DEBUG_FLOW_POSITION_DELTA

//#define DEBUG_TOF_DISTANCE
//#define DEBUG_TOF_HEIGHT

//#define DEBUG_POSITON_CONTROL
//#define DEBUG_ATTITUDE_CONTROL
//#define DEBUG_ANGVEL_CONTROL

//#define DEBUG_PID_COMMAND
//#define DEBUG_RECV_COMMAND
//#define DEBUG_ANGVEL_COMMAND
//#define DEBUG_MOTOR_COMMAND